import generate_fno_files as rm
import update_records_fno
from os import listdir
from os.path import isfile, join


STOCK_LIST = [
                'ACC',
              'ADANIENT',
              'ADANIPORTS',
              'AMARAJABAT',
              'AMBUJACEM',
              'APLLTD',
              'APOLLOHOSP',
              'APOLLOTYRE',
              'ASHOKLEY',
              'ASIANPAINT',
              'AUROPHARMA',
              'AXISBANK',
              'BAJAJ-AUTO',
              'BAJAJFINSV',
              'BAJFINANCE',
              'BALKRISIND',
              'BANKBARODA',
              'BATAINDIA',
              'BEL',
              'BERGEPAINT',
              'BHARATFORG',
              'BHARTIARTL',
              'BHEL',
              'BIOCON',
              'BOSCHLTD',
              'BPCL',
              'BRITANNIA',
              'CADILAHC',
              'CANBK',
              'CHOLAFIN',
              'CIPLA',
              'COALINDIA',
              'COFORGE',
              'COLPAL',
              'CONCOR',
              'COROMANDEL',
              'CUMMINSIND',
              'DABUR',
              'DEEPAKNTR',
              'DIVISLAB',
              'DLF',
              'DRREDDY',
              'EICHERMOT',
              'ESCORTS',
              'EXIDEIND',
              'GAIL',
              'GLENMARK',
              'GMRINFRA',
              'GODREJCP',
              'GODREJPROP',
              'GRANULES',
              'GRASIM',
              'GUJGASLTD',
              'HAVELLS',
              'HCLTECH',
              'HDFC',
              'HDFCAMC',
              'HDFCBANK',
              'HDFCLIFE',
              'HEROMOTOCO',
              'HINDALCO',
              'HINDPETRO',
              'HINDUNILVR',
              'IBULHSGFIN',
              'ICICIBANK',
              'ICICIPRULI',
              'IGL',
              'INDIGO',
              'INDUSINDBK',
              'INFY',
              'IOC',
              'IRCTC',
              'ITC',
              'JINDALSTEL',
              'JSWSTEEL',
              'JUBLFOOD',
              'KOTAKBANK',
              'LALPATHLAB',
              'LICHSGFIN',
              'LT',
              'LTI',
              'LTTS',
              'LUPIN',
              'M&M',
              'M&MFIN',
              'MANAPPURAM',
              'MARICO',
              'MARUTI',
              'MCDOWELL',
              'METROPOLIS',
              'MFSL',
              'MGL',
              'MINDTREE',
              'MOTHERSUMI',
              'MPHASIS',
              'MRF',
              'MUTHOOTFIN',
              'NATIONALUM',
              'NAUKRI',
              'NAVINFLUOR',
              'NESTLEIND',
              'NMDC',
              'NTPC',
              'ONGC',
              'PAGEIND',
              'PEL',
              'PETRONET',
              'PFC',
              'PFIZER',
              'PIDILITIND',
              'PIIND',
              'PNB',
              'POWERGRID',
              'PVR',
              'RAMCOCEM',
              'RBLBANK',
              'RECLTD',
              'RELIANCE',
              'SAIL',
              'SBILIFE',
              'SBIN',
              'SHREECEM',
              'SIEMENS',
              'SRF',
              'SRTRANSFIN',
              'STAR',
              'SUNPHARMA',
              'SUNTV',
              'TATACHEM',
              'TATACONSUM',
              'TATAMOTORS',
              'TATAPOWER',
              'TATASTEEL',
              'TCS',
              'TECHM',
              'TITAN',
              'TORNTPHARM',
              'TORNTPOWER',
              'TVSMOTOR',
              'UBL',
              'ULTRACEMCO',
              'UPL',
              'VEDL',
              'VOLTAS',
              'WIPRO',
              'ZEEL']

def generate_all_fno_files():
    for stock in STOCK_LIST:
        rm.generate_complete_csv(stock)


def update_all_files():
    FOLDER_LOCATION = "D:\\Market\\Excels\\PositionAnalysis\\"

    # It will contain file extension
    all_files = [f for f in listdir(FOLDER_LOCATION) if isfile(join(FOLDER_LOCATION, f))]
    for f in all_files:
        update_records_fno.update_files(f.split(".")[0], FOLDER_LOCATION + f)

# generate_all_fno_files()
update_all_files()